/etc/samba/smb.conf
/etc/samba/smbinfo.conf
/etc/samba/smb.reserved.conf
/etc/samba/smb.share.conf
/usr/syno/etc/private/adsinfo
/usr/syno/etc/private/diagnose
/usr/syno/etc/private/domain_info
/usr/syno/etc/private/domain_list
/usr/syno/etc/private/domain_list.group
/usr/syno/etc/private/domain_list.user
/usr/syno/etc/private/kdc_ip
/usr/syno/etc/private/last_join_info
/usr/syno/etc/private/trust_domain_info
/usr/syno/etc/private/workgroup
