set nocompatible
set encoding=utf-8
set softtabstop=4
set tabstop=4
set shiftwidth=4
set undolevels=1024
set history=64
set modelines=32
set modeline
set backup
set ruler
set showmatch
set hlsearch
set incsearch
set ignorecase
set smartcase
set autoindent
set backspace=indent,eol,start
set wildmenu
set showcmd
set nobackup
set nofoldenable

filetype indent plugin on
syntax on

map <PageUp> <C-u>
map <PageDown> <C-d>
imap <PageUp> <C-o><C-u>
imap <PageDown> <C-o><C-d>

inoremap <Esc>Oq 1
inoremap <Esc>Or 2
inoremap <Esc>Os 3
inoremap <Esc>Ot 4
inoremap <Esc>Ou 5
inoremap <Esc>Ov 6
inoremap <Esc>Ow 7
inoremap <Esc>Ox 8
inoremap <Esc>Oy 9
inoremap <Esc>Op 0
inoremap <Esc>On .
inoremap <Esc>OQ /
inoremap <Esc>OR *
inoremap <Esc>Ol +
inoremap <Esc>OS -
inoremap <Esc>OM <Enter>

